language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
before_install:
  - wget http://ftp.us.debian.org/debian/pool/main/r/ragel/ragel_6.7-1.1_i386.deb
  - sudo dpkg -i ragel_6.7-1_i386.deb
notifications:
  irc: "irc.freenode.org#adhearsion"
